#!/bin/bash

# a script to get viewing coords of solar system bodies

year=$(TZ=UTC date +%Y)
month=$(TZ=UTC date +%m)
day=$(TZ=UTC date +%d)
hr=$(TZ=UTC date +%H)
min=$(TZ=UTC date +%M)
sec=$(TZ=UTC date +%S)

body="$1"

aa << EOF | sed -n '/Altitude/{s/.*Altitude -.*/Not visible/p;s/.*Altitude [0-9].*/Visible/p}'
$year
$month
$day
$hr
$min
$sec
1
1
$body
EOF

