#!/bin/bash

# a script to get viewing coords of the sun

year=$(date -u +%Y)
month=$(date -u +%m)
day=$(date -u +%d)
hr=$(date -u +%H)
min=$(date -u +%M)
sec=$(date -u +%S)

body="$1"

aa << EOF | sed -n '/Topocentric:  Al/{s/Topocentric: //; s/-  /-/; s/Altitude //; s/Azimuth //; s/, / \/ /; s/\(\.[0-9][0-9]\)[0-9]/\1/g; s/^ *//; s/ deg/°/gp}'
$year
$month
$day
$hr
$min
$sec
1
1
88

$body
EOF
